### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [kungfubeaner/mpv-ontop-only-while-playing-lua#2]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by kungfubeaner** [comment]
I had been super busy all year at a new job so I just now saw this.  Sorry about the late response but I see the script is already there.
